services:
  minecraft-server-proxy:
    image: ${MINECRAFT_SERVER_IMAGE_TAG}
    volumes:
      - ./minecraft-server-proxy-data:/server
      - ./plugins:/plugins:ro
      # Adjust the path to 'velocity.toml' based on your operating system:
      # For Linux or macOS:
      - ./velocity.toml:/config
      
      # For Windows:
      # Uncomment the line below and comment out the '- ./velocity.toml:/config' line.
      # - ./velocity.toml:/config/velocity.toml
    environment:
      TYPE: ${MINECRAFT_SERVER_TYPE}
      MEMORY: ${MINECRAFT_SERVER_MEMORY}
    ports:
      - "${MINECRAFT_SERVER_PORT}:${MINECRAFT_SERVER_PORT}"
      - "${MINECRAFT_BEDROCK_SERVER_PORT}:${MINECRAFT_BEDROCK_SERVER_PORT}/udp"
    restart: unless-stopped
